- hosts: local1s
  become: true

  tasks:

    - name: debugging
      debug:
        msg: "{{ packs}}"

    - name: Installing packages
      yum:
        name: "{{packs}}"
        state: "installed"
